### ISSUE TITLE
Library is not working on RN 0.60

### ISSUE THREAD

**Issue by mikaoelitiana** [teamairship/react-native-android-fullscreen-webview-video#27]
I am upgrading my RN project to RN 0.60 and got the following error from react-native-android-fullscreen-webview-video when compiling : 

```
/node_modules/react-native-android-fullscreen-webview-video/android/src/main/java/com/airship/customwebview/CustomWebViewManager.java:55: error: package com.facebook.react.views.webview does not exist
import com.facebook.react.views.webview.WebViewConfig;
                                       ^
```

**Comment by adambeck7** [comment]
Having the same issue.

**Comment by erenilhan** [comment]
Same issue +1

**Comment by mikaoelitiana** [comment]
I have fixed this issue and created a PR #28 but now I am getting another issue : 
```
Requiring module "index.android.js", which threw an exception: Invariant Violation: Tried to register two views with the same name RNCWebView
```

**Comment by mikaoelitiana** [comment]
I finally found the cause of this last issue, I had to set same version of `react-native-webview` in my root project as in `react-native-android-fullscreen-webview-video`:

```
"react-native-webview": "^5.12.1",
```

**Comment by nguyen95** [comment]
Please merge pull request from @mikaoelitiana

**Comment by amhinson** [comment]
It looks like react-native-webview supports fullscreen Android video now, so there might actually not be a need for this library anymore:
https://github.com/react-native-community/react-native-webview/pull/325

**Comment by mikaoelitiana** [comment]
@amhinson thanks for pointing that. I will try if this is working.

**Comment by kesepara** [comment]
@mikaoelitiana can you confirm that if react native's webview supports that?

**Comment by mikaoelitiana** [comment]
Yes as far as I know it works fine

**Comment by igaidai4uk** [comment]
The quickest fix is to change in `iosWebView.js`
```javascript
import { WebView } from 'react-native';
```
to 
```javascript
import { WebView } from 'react-native-webview';`
```
And yes `react-native-webview` has to be installed.

**Comment by loukrath** [comment]
I got some error after I run `react-native run-android`.
+ **Error message:** 
   - Task :react-native-android-fullscreen-webview-video:compileDebugJavaWithJavac FAILED
   - Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
   - com.facebook.react.views.webview.WebViewConfig
   - com.facebook.react.views.webview.events.TopLoadingErrorEvent
   - dispatchEvent(this, new TopMessageEvent(this.getId(), message))

+ Version:
   - react-native: 0.61.2
   - react-native-android-fullscreen-webview-video: 1.0.3
   - react-native-webview: 5.8.1

**Comment by amhinson** [comment]
@loukrath I'd recommend just using `react-native-webview`, as they've [added support ](https://github.com/react-native-community/react-native-webview/pull/325)for precisely what this library was created for.

**Comment by loukrath** [comment]
> @loukrath I'd recommend just using `react-native-webview`, as they've [added support ](https://github.com/react-native-community/react-native-webview/pull/325)for precisely what this library was created for.

It works for me, thanks
